import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";

const Products = () => {
  const [products, setProducts] = useState([]);
  const [filter, setFilter] = useState(null);

  useEffect(() => {
    const getProducts = async () => {
      try {
        const url = filter
          ? `/api/products?category=${filter}`
          : "api/products";
        const response = await fetch(url);
        if (response.ok) {
          const data = await response.json();
          setProducts(data);
        } else {
          throw new Error(`Fetch failed, status: ${response.status}`);
        }
      } catch (error) {
        console.log(error);
        alert(error.message);
      }
    };
    getProducts();
  }, [filter]);

  const uniqueCategories = [
    ...new Set(products.map((product) => product.category)),
  ];

  console.log(filter);
  console.log(products);

  return (
    <>
      <Head>
        <title>Product Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Products Dashboard</div>
      <div>
        <label htmlFor="categories">Select a filter:</label>
        <select
          name="categories"
          id="categories"
          onChange={(event) => {
            if (event.target.value === "") {
              setFilter(null);
            } else {
              setFilter(event.target.value);
            }
          }}
        >
          <option value="">Show all</option>
          {uniqueCategories.map((category) => {
            return (
              <>
                <option value={category}>{category}</option>
              </>
            );
          })}
        </select>
      </div>
      <ul>
        {products.map((product) => {
          return (
            <li key={product.id}>
              <Link href={`/products/${product.id}`}>{product.name}</Link>
            </li>
          );
        })}
      </ul>
    </>
  );
};

export default Products;
